name: Deploy MCSD Project to Amazon ECS

#on:
#  pull_request:
#  # push:
#    branches:
#      - master

on:
  pull_request:
    types:
      - closed

env:
  AWS_REGION: ap-southeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mcsd-project         # set this to your Amazon ECR repository name
  ECS_SERVICE: mcsd-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: mcsd-ecs-cluster               # set this to your Amazon ECS cluster name
  CONTAINER_NAME: mcsd-container          # set this to the name of the container in the
                                          # containerDefinitions section of your task definition
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |

        GIT_BUILD=$(git describe --all --long | tr "-" " " | awk '{ print $3 }')

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_BUILD -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_BUILD
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


    # Uncomment to DEPLOY
#    - name: Deploy updated container
#      run: |
#        GIT_BUILD=$(git describe --all --long | tr "-" " " | awk '{ print $3 }')
#        aws cloudformation deploy --stack-name mcsd-ecs-stack \
#        --template-file _infra/ecs.yaml \
#        --region ap-southeast-2 \
#        --no-fail-on-empty-changeset \
#        --parameter-overrides ImageVersion=$GIT_BUILD \
#        --capabilities CAPABILITY_NAMED_IAM